### ISSUE TITLE
Range category of homomorphism structure depends on option `no_precompiled_code`

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/Algebroids#137]
The range category `H` of the homomorphism structure of an Algebroid is used as a default range category of the functor category constructor. The doctrines of the resulting functor category depend on the doctrines of `H`. In the current code introduced in the following commit

https://github.com/homalg-project/Algebroids/blob/16d55a4ef5f957cc1c5c59c8eb9e389412593acf/gap/Algebroids.gi#L749-L757

the choice of `H` depends on the option `no_precompiled_code`. In case the latter is set to true (for the first time by the tests in this [PR](https://github.com/homalg-project/FunctorCategories/pull/140)), then a functor category which is expected to be Abelian is missing kernels and cokernels since they are missing in `H = MatrixCategoryAsAdditiveClosureOfRingAsCategory( Q )`.

**Comment by zickgraf** [comment]
`MatrixCategory` uses homalg matrices as the internal data structure while `MatrixCategoryAsAdditiveClosureOfRingAsCategory` uses GAP matrices (lists of lists) as the internal data structure. The homomorphism structure in Algebroids essentially creates lots of small matrices (many of which are zero matrices) and stacks/augments them. Due to the design of MatricesForHomalg, this is very slow for homalg matrices and much faster for lists of lists. That's why the compilation uses `MatrixCategoryAsAdditiveClosureOfRingAsCategory`. The result is fully compatible with chosing `MatrixCategory`, so in case that one wants to compute lifts etc., in the usual (i.e. "non-compilation") case, `MatricCategory` is used.

**Comment by mohamed-barakat** [comment]
Thanks for the clarification.
